# Generated by Django 5.0.4 on 2024-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditcard',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=255, primary_key=True, serialize=False)),
                ('time', models.FloatField(blank=True, db_column='Time', null=True)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('v1', models.FloatField(blank=True, db_column='V1', null=True)),
                ('v2', models.FloatField(blank=True, db_column='V2', null=True)),
                ('v3', models.FloatField(blank=True, db_column='V3', null=True)),
                ('v4', models.FloatField(blank=True, db_column='V4', null=True)),
                ('v5', models.FloatField(blank=True, db_column='V5', null=True)),
                ('v6', models.FloatField(blank=True, db_column='V6', null=True)),
                ('v7', models.FloatField(blank=True, db_column='V7', null=True)),
                ('v8', models.FloatField(blank=True, db_column='V8', null=True)),
                ('v9', models.FloatField(blank=True, db_column='V9', null=True)),
                ('v10', models.FloatField(blank=True, db_column='V10', null=True)),
                ('v11', models.FloatField(blank=True, db_column='V11', null=True)),
                ('v12', models.FloatField(blank=True, db_column='V12', null=True)),
                ('v13', models.FloatField(blank=True, db_column='V13', null=True)),
                ('v14', models.FloatField(blank=True, db_column='V14', null=True)),
                ('v15', models.FloatField(blank=True, db_column='V15', null=True)),
                ('v16', models.FloatField(blank=True, db_column='V16', null=True)),
                ('v17', models.FloatField(blank=True, db_column='V17', null=True)),
                ('v18', models.FloatField(blank=True, db_column='V18', null=True)),
                ('v19', models.FloatField(blank=True, db_column='V19', null=True)),
                ('v20', models.FloatField(blank=True, db_column='V20', null=True)),
                ('v21', models.FloatField(blank=True, db_column='V21', null=True)),
                ('v22', models.FloatField(blank=True, db_column='V22', null=True)),
                ('v23', models.FloatField(blank=True, db_column='V23', null=True)),
                ('v24', models.FloatField(blank=True, db_column='V24', null=True)),
                ('v25', models.FloatField(blank=True, db_column='V25', null=True)),
                ('v26', models.FloatField(blank=True, db_column='V26', null=True)),
                ('v27', models.FloatField(blank=True, db_column='V27', null=True)),
                ('v28', models.FloatField(blank=True, db_column='V28', null=True)),
                ('class_field', models.IntegerField(blank=True, db_column='Class', null=True)),
            ],
            options={
                'db_table': 'creditcard',
            },
        ),
    ]
